
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE 
    username: sa
    password: 
  mail:
    host : backendsmtp.naver.com
    port : 25
    

db:
  source:
    host: 10.127.45.75
    database: pfms
    user: pfm_dev
    password: pfm1234
    port: 20306
  target:
    host: 10.127.198.47
    database: pfms
    user: pfms_dev
    password: pfms1234
    port: 20306
    
    
---
spring:
  profiles: rc
    